### ISSUE TITLE
responsive css path was wrong

### ISSUE THREAD

**Issue by arnoldbird** [phanbook/phanbook#212]
I'm installing phanbook on LAMP.

I was having a problem with the default theme, where the path to the theme.css was correct but the path to responsive.css was wrong...

```
<!-- Main Style -->
    <link rel="stylesheet" type="text/css" href="/css/theme.css?v=1" />

    <!-- Responsive Style -->
    <link rel="stylesheet" href="/core/assets/css/responsive.css">
```
This was after installing on LAMP with the manual instructions:  http://phanbook.com/docs/manual

To fix it, I made a symbolic link in public to core...

`me@here:/var/www/phanbook/public$ sudo ln -s ../core core`

But is that a normal part of the install?  When I ran the composer command, should it have put the core directory inside the public directory?

**Comment by Ultimater** [comment]
I believe you're confusing the intended directory structure. The `public` directory in the project is supposed to be redirected to by .htaccess only. Thus there's two .htaccess files in the project. So in other words, you're supposed to copy-paste all the files in the repo and toss them all into your web root, in public view. Then .htaccess forwards everything to `/public`. This allows `/css/theme.css?v=1` and `/core/assets/css/responsive.css` to both be accessed, because the root-most .htaccess file contains:  

    RewriteRule ^(core/assets)($|/) - [NC,L]
    RewriteRule ^(content/themes)($|/) - [NC,L]

While the /public/.htaccess file does the actual rewriting to the /public/index.php file.  

/cc @sergeyklay This is not a bug, just the installation docs could be slightly more clear regarding what's supposed to be exposed to the web and what isn't. We're aiming at stability at the moment. We can tackle docs later.
