### ISSUE TITLE
Phanbook redesign

### ISSUE THREAD

**Issue by duythien** [phanbook/phanbook#7]
Hi there

Currently, we have some theme but that not good so we need to redesign it
- Material redesign
- Flat redesign 

Here some article good for you
- [Reddit redesign concept](https://medium.com/@stothelios/reddit-redesign-concept-913aa552124e)
##

**Comment by sergeyklay** [comment]
+1

**Comment by pompaskin** [comment]
Hi!

I want to share my first draft/ideas about the redesign of Phanbook and see what do you think.

The first thing I’ve done is to think how the navigations were made.

I’ve separated the navigation in two main different sections, I see a difference between the general actions of the navigation and the “filtering” actions who are related directly to the content of the web. 

As you can see I’ve created a web navigation on the top to navigate inside the website, and a filter to navigate through the content of the questions/discussions.

On the actual design some actions are repeated on the second top navigation and also on the right dropdown like “unanswered” or “hot” , so In this design I unified them into just one section. I think this “second navigation” is more a filter, because this sections will not apear behind the section “users” or “tags” for example (as I understand).

I also thought about unifying some actions on the top left dropdown of the user. For example “Change password” and “Change your avatar” are usually actions that you find inside sections, so maybe they could be grouped there.

I’m looking forward to see what do you think and if you have any other ideas how to improve that. For now I've just added the thins I see are on the beta version but let me know if there should be more elements added on the homepage etc.

[Phanbook-home.pdf](https://github.com/phanbook/phanbook/files/142807/Phanbook-home.pdf)

**Comment by duythien** [comment]
For now:

You right

> I think this “second navigation” is more a filter, because this sections will not apear behind the section “users” or “tags” for example (as I understand). 

The elements for homepage it will not change and it is  enough right now, I think you should  add more icon or color for the questions have a answer which is accepted to highline this

> I see are on the beta version but let me know if there should be more elements added on the homepage etc.

**Comment by duythien** [comment]
@pompaskin Anything update :)

**Comment by pompaskin** [comment]
Hey @duythien sorry, i've been a bit busy lately, I'll update you as soon as posible :)

**Comment by duythien** [comment]
No problem

**Comment by pompaskin** [comment]
Hi!

If we want to give colors to the tags I will need a list of all the tags that exist to choose the color that represents each tag.

One question that I have is, what is more important in Phanbook, the upvotes, the comments or both have the same importance? 

For example on reddit it seems to be the upvotes (as you can see they have the number big on the left and the comments go on the right side smaller). But for Stack Overflow the importance is the same + views, I will need to know because on the design I sent last time I gave more importance to the upvotes but I don't know if It's right.

Thanks!

**Comment by duythien** [comment]
Hi

> If we want to give colors to the tags I will need a list of all the tags that exist to choose the color that represents each tag.

With a post it is max 5 tags, you can create tag to test

> One question that I have is, what is more important in Phanbook, the upvotes, the comments or both have the same importance? 

I think the comment(it mean the answers) it is import for Q&A site, just my opinion

**Comment by pompaskin** [comment]
Hey! I've tried a few things for the homepage and I've started also with the detail page.

This green color is just a test, I wanted to try something different that look more "flat" you can tell me what you think. In this website you can see more flat colors: http://www.flatuicolorpicker.com/

I think all the tags should have the same color, because if we add a lot of colors can be too distractive.

On the detail page of the question I think we can leave the right sidebar empty for now and then add some information we may need. We could also a button for ask a question or add there the sharing buttons.

What do you think??

[Phanbook-Detail Page.pdf](https://github.com/phanbook/phanbook/files/167128/Phanbook-Detail.Page.pdf)
[Phanbook-home-2.pdf](https://github.com/phanbook/phanbook/files/167129/Phanbook-home-2.pdf)

**Comment by sergeyklay** [comment]
Looks good to me

**Comment by duythien** [comment]
Hi

> I think all the tags should have the same color, because if we add a lot of colors can be too distractive.

I completely agree.

> On the detail page of the question I think we can leave the right sidebar empty for now and then add some information we may need. We could also a button for ask a question or add there the sharing buttons.

Yes, we can leave the right sidebar empty and we can add the sharing button for it , so I think it is ok

**Comment by glmanhtu** [comment]
@pompaskin Well, I think your design templates's very interesting. However, in Phanbook detail page, I think we've two kind of the answer. The first one is comment and the second one is real answer for the question (just like StackOverflow). If we show all of the answers, so, it will make difficult for user, who want to looking for the real answer, and so on. 
In Phanbook home page, it look pretty nice but, it have too many space. How do you think if we have a new column in the right of page, may be for hot question or article ?

**Comment by pompaskin** [comment]
Hi @yehnkay I'm happy that you like the designs!

_"The first one is comment and the second one is real answer for the question (just like stack over flow). If we show all of the answers, so, it will make difficult for user, who want to looking for the real answer, and so on."_

Regarding to this for now I'm just designing the pages I see that exist. I didn't know there are 2 kind of answers, could you send me a link with the two different examples so I can see the designs that need to be done? Thanks! :)

_In Phanbook home page, it look pretty nice but, it have too many space. How do you think if we have a new column in the right of page, may be for hot question or article ?_

For now I'm just designing with the elements that are on the actual page, after we can try to add more elements like the sidebar you say and see how that looks etc. I was also thinking maybe we could add a button saying "Ask question" so people are more engaged to participate and to ask questions etc. But I think we can add all these elements after we have all the structure :)

**Comment by duythien** [comment]
Hi

> Regarding to this for now I'm just designing the pages I see that exist. I didn't know there are 2 kind of answers, could you send me a link with the two different examples so I can see the designs that need to be done? Thanks! :)

You can see at http://dev.phanbook.com/questions/66/phalcon-zephir-funding-campaign

**Comment by pompaskin** [comment]
Hey @duythien and @yehnkay  I'm confused with the detail page design, I don't see the difference between the last link you send me and what @yehnkay said here about the design I uploaded last time: 
_
"However, in Phanbook detail page, I think we've two kind of the answer. The first one is comment and the second one is real answer for the question (just like StackOverflow). If we show all of the answers, so, it will make difficult for user, who want to looking for the real answer, and so on. "_

He says there are 2 kinds of answers, but I just see one type of design of the detail page with these elements:

Title

Question
Comments (answers)

**Comment by glmanhtu** [comment]
Hmm, ok. This is my fault, I haven't show my opinion in clearly way to you. So, you can see at the link, which @duythien has sent. The first kind of answer just is a comment and it don't have up & down vote button. The second one have bigger font size. To be clear, you can look at the photo in attachment which I was marked about which one is comment and which one is real answer.

Have a nice day :)
![screen shot 2016-03-21 at 6 28 04 pm](https://cloud.githubusercontent.com/assets/6909106/13917729/23d32a36-ef95-11e5-804e-51efeed863d7.png)

**Comment by pompaskin** [comment]
Hey @yehnkay Thank you for your answer! :) I get it now, I will adapt the design to give more importance to the first answer.

Have a nice day you too!

**Comment by pompaskin** [comment]
I've adapted the design of the detail question page, On the sidebar I've tried to add the social icons on the top and also to have a "ask question" button on the side + some hot questions as @yehnkay suggested for the homepage.

I also did the ask question page and the Tags page, on the tags I've put the number of posts/questions that are inside each topic next to the name of the tag.

What do you think??

[Phanbook-Ask Page.pdf](https://github.com/phanbook/phanbook/files/183868/Phanbook-Ask.Page.pdf)
[Phanbook-Detail Page.pdf](https://github.com/phanbook/phanbook/files/183869/Phanbook-Detail.Page.pdf)
[Phanbook-Tags Page.pdf](https://github.com/phanbook/phanbook/files/183870/Phanbook-Tags.Page.pdf)

**Comment by duythien** [comment]
Hello

I have edit some element in this pdf file below, you can take look it
[Phanbook-Detail.Page(1).pdf](https://github.com/phanbook/phanbook/files/185305/Phanbook-Detail.Page.1.pdf)

And I see the Tags and Ask files look good

**Comment by pompaskin** [comment]
Hi @duythien I will adapt the file with your changes :)

I wanted to ask you, we just have left to do the users page? And when do you think you will implement the designs?

**Comment by duythien** [comment]
Hi @pompaskin 

Well If you have idea for users page you can add design for it:), for now I have just sample layout for it http://dev.phanbook.com/users

And we have done design I will implement it

**Comment by pompaskin** [comment]
Hii guys! Sorry for the delay, here is the adapted design for the detail page and the user page design. For the users I've used something really similar to what you have designed, I think the design is good like that. What do you think?

[Phanbook-Detail Page.pdf](https://github.com/phanbook/phanbook/files/202069/Phanbook-Detail.Page.pdf)
[Phanbook-Users Page.pdf](https://github.com/phanbook/phanbook/files/202070/Phanbook-Users.Page.pdf)

**Comment by duythien** [comment]
@pompaskin That look good, so what about for mobile phone version?

**Comment by pompaskin** [comment]
Hey @duythien I'm working on the mobile designs, when I have all of them I'll upload them here

**Comment by pompaskin** [comment]
Hi, I have two of the mobile designs, for the homepage and for the page of the question. When would you start doing the frontend of the first theme??

[Mobile Detail Page.pdf](https://github.com/phanbook/phanbook/files/223323/Mobile.Detail.Page.pdf)
[Mobile Homepage.pdf](https://github.com/phanbook/phanbook/files/223324/Mobile.Homepage.pdf)

**Comment by duythien** [comment]
@pompaskin Currently I'm busy but I tried to start doing it at saturday this week,by the way what is tool you create this mockup?

**Comment by pompaskin** [comment]
@duythien I'm using sketch for the designs, if you need I can send you the original files or something

**Comment by duythien** [comment]
@pompaskin Right now I think this theme is ok so you don't need create layout for mobile, thank you for you contribution :) :+1:
