### ISSUE TITLE
Introduce separated error handler

### ISSUE THREAD

**Issue by sergeyklay** [phanbook/phanbook#72]

**Comment by captbrogers** [comment]
What kind of error handling would you like to see implemented?

**Comment by sergeyklay** [comment]
@captbrogers I wold like to use something like https://filp.github.io/whoops/

**Comment by Ultimater** [comment]
Yeah, we need a good way to accomplish this sort of thing.
While it's pretty easy to write three lines in our bootstrap
```
$whoops = new \Whoops\Run;
$whoops->pushHandler(new \Whoops\Handler\PrettyPageHandler);
$whoops->register();
```
Do we really want to be using the "pretty page handler" though and risk that sort of information spilling into production, getting viewed by others? Enable/disable by config and limit by ip address in a whitelist perhaps?

Otherwise it seems like a perfect debugging tool that makes life really easy.

**Comment by sergeyklay** [comment]
@Ultimater 

- [Phalcon Phosphorum](https://github.com/phalcon/forum/blob/3.x/app/provider/ErrorHandler/ServiceProvider.php)
- [Phalcon Docs App](https://github.com/phalcon/docs-app/blob/master/app/providers/ErrorHandler/ServiceProvider.php)
